mobile.database.database=mobile
mobile.database.driverClassName=com.mysql.cj.jdbc.Driver
mobile.database.username=root
mobile.database.password=123456
mobile.database.show_sql=true
mobile.database.url=jdbc:mysql://localhost:3306/mobile?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

unicom.database.database=unicom
unicom.database.driverClassName=com.mysql.cj.jdbc.Driver
unicom.database.username=root
unicom.database.password=123456
unicom.database.show_sql=true
unicom.database.url=jdbc:mysql://localhost:3306/unicom?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC

telecom.transfer.service.address=http://localhost:8081/services/TransferSupportService
